config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'pages#index'
  get 'users/new'
  get 'quizzes/opening'
  get 'quizzes/select/:genre_id', to: 'quizzes#select'
  get 'quizzes/answer'
  get 'quizzes/result/:id/:answer', to: 'quizzes#result'
  get 'quizzes/new'
  get 'quizzes/:id', to: 'quizzes#show'
  get 'genres/select'
  post 'quizzes/create',  to: 'quizzes#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quiz.rb
class Quiz < ApplicationRecord
    
    
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    has_secure_password
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    add_flash_types :success, :info, :warning, :danger
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def logged_in?
      !current_user.nil?
    end
  end
  

app/controllers/concerns/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
  
    def help
    end
  end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def select
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def opening
  end
  def select
    genre_id= params[:genre_id]
    @quizes = Quiz.where(genre_id: genre_id)
  end
  def show
    @quiz = Quiz.find params[:id]
  end
  def answer
  end
  def result
    @quiz = Quiz.find params[:id]
    logger.debug params[:answer]
    logger.debug @quiz.answer
    if params[:answer].to_i == @quiz.answer
       @text = '正解'
    else 
       @text = '不正解'  
    end 
    @answer_text
    case @quiz.answer
    when 1
    @answer_text = @quiz.choice_1
    when 2
    @answer_text = @quiz.choice_2
    when 3
    @answer_text = @quiz.choice_3
    when 4
    @answer_text = @quiz.choice_4
    end
  end
  def new
    @quiz = Quiz.new
  end
  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.user_id = current_user.id
    if @quiz.save
      logger.debug "if"
            redirect_to quizzes_opening_path
    else
      logger.debug "else"
         render :new
    end
  end
  private
  def quiz_params
    params.require(:quiz).permit(:genre_id, :title, :question, :choice_1, :choice_2, :choice_3,:choice_4,:answer)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to quizzes_opening_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      #render :new
      redirect_to sessions_new_path, danger: 'ログインに失敗しました'
    end
  end
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    logger.debug  params[:user][:name]
    logger.debug  params[:user][:email]
    if @user.save
      logger.debug "if"
            redirect_to root_path
    else
      logger.debug "else"
         render :new
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def logged_in?
      !current_user.nil?
    end
  end
  
  

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genres/select.html.erb
 <div class="row">
<div class="col">
  
</div>
<div class="col">
  <div class="" style="margin-top:250px;">
<div>
  <a href="/quizzes/select/1" style="font-size:35px;" class="">勉強</a>
</div>
 <div>
  <a href="/quizzes/select/2" style="font-size:35px;" class="">趣味</a>
</div>
 <div>
  <a href="/quizzes/select/3" style="font-size:35px;" class="">その他</a>
</div>
  </div>
</div>
<div class="col">
  
</div>
</div>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        
        <a href="/users/new" style="font-size:35px;" class="btn btn-block btn-white"> 
         Sign up 
        <a>
      </div>
      <div class="col-md-3"> 
       <a href="/login" style="font-size:35px;" class="btn btn-block btn-white"> 
       Log in
        <a>
      

      </div>
    </div>
  </div>
</div>

app/views/quizzes/answer.html.erb
answer

app/views/quizzes/new.html.erb
<%= form_for @quiz, url:quizzes_create_path do |f| %>
   <div class="mb-3" style="width:300px;">
    <%= f.label :genre_id, "ジャンル" %>
     <%= f.select :genre_id, {勉強: 1, 趣味: 2, その他: 3}, {include_blank: '選択してください'} %>
  </div>
  <div class="mb-3" style="width:300px;">
      <%= f.label :title, "タイトル" %>
            <%= f.text_field :title, class: 'form-control' %>
  </div>
   <div class="mb-3">
     <%= f.label :question, "問題文" %>
            <%= f.text_area :question, class: 'form-control',size: "150x3" %>   
  <div class="mb-3" style="width:300px;">
     <%= f.label :choice_1, "選択肢1" %>
            <%= f.text_field :choice_1, class: 'form-control' %>
  </div><div class="mb-3" style="width:300px;">
     <%= f.label :choice_2, "選択肢2" %>
            <%= f.text_field :choice_2, class: 'form-control' %>
  </div><div class="mb-3" style="width:300px;">
     <%= f.label :choice_3, "選択肢3" %>
            <%= f.text_field :choice_3, class: 'form-control' %>
  </div><div class="mb-3" style="width:300px;">
     <%= f.label :choice_4, "選択肢4" %>
            <%= f.text_field :choice_4, class: 'form-control' %>
    </div><div class="mb-3" style="width:300px;">
    <%= f.label :answer, "  答え" %>
     <%= f.select :answer, {選択肢1: 1, 選択肢2: 2, 選択肢3: 3,選択肢4: 4}, {include_blank: '選択してください'} %>
  </div>
 <%= f.submit "完了", class: 'btn-block btn-white' %>
<% end %>

app/views/quizzes/opening.html.erb
<div class="row">
<div class="col">
  
</div>
<div class="col">
  <div class="d-flex align-items-center mt-10" style="margin-top:250px;">
    <a href="/quizzes/new" class="btn btn-primary btn-lg" style="margin-right:20px;">作る</a>
    <a href="/genres/select" class="btn btn-success btn-lg">解く</a>
  </div>
</div>
<div class="col">
  
</div>
</div>

app/views/quizzes/result.html.erb
<div style="margin-left:100px; margin-top:200px">
<%=@text%>
</div>
<div style="margin-left:100px">
解答は<%=@answer_text%>
</div>
<a href="/quizzes/opening" style="margin-left:100px" class="btn btn-danger btn-lg">戻る</a>

app/views/quizzes/select.html.erb
 <% @quizes.each do |quiz| %>
<div style="margin-left:10px; overflow-wrap: break-word;">
 <a href="/quizzes/<%=quiz.id%>" style="font-size:35px;" ><%=quiz.title%></a>
</div>
<% end %>

app/views/quizzes/show.html.erb
<div style="margin-left:100px">
<%=@quiz.title%>
</div>
<div>
<%=@quiz.question%>
</div>
<div style="margin-left:100px">
<div>
<a href="/quizzes/result/<%=@quiz.id%>/1" class="btn btn-secondary btn-lg"><%=@quiz.choice_1%></a>
</div>
<div>
<a href="/quizzes/result/<%=@quiz.id%>/2" class="btn btn-secondary btn-lg"><%=@quiz.choice_2%></a>
</div>
<div>
<a href="/quizzes/result/<%=@quiz.id%>/3" class="btn btn-secondary btn-lg"><%=@quiz.choice_3%></a>
</div>
<div>
<a href="/quizzes/result/<%=@quiz.id%>/4" class="btn btn-secondary btn-lg"><%=@quiz.choice_4%></a>
</div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, "名前" %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
             <%= f.label :email, "メールアドレス" %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, "パスワード" %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
             <%= f.label :password_confirmation, "パスワード確認" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
         <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>